// <auto-generated />
using MemGen.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MemGen.Migrations
{
    [DbContext(typeof(Connection))]
    [Migration("20211026191751_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("MemGen.Model.Imagen", b =>
                {
                    b.Property<int>("ImagenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<double>("Peso")
                        .HasColumnType("REAL");

                    b.Property<string>("URL")
                        .HasColumnType("TEXT");

                    b.HasKey("ImagenID");

                    b.ToTable("Imagenes");

                    b.HasData(
                        new
                        {
                            ImagenID = 1,
                            Nombre = "SpongeBob_Walking",
                            Peso = 0.0,
                            URL = "https://plantillasdememes.com/img/plantillas/bob-esponja-entrando-por-la-puerta-al-salon01565047441.jpg"
                        },
                        new
                        {
                            ImagenID = 2,
                            Nombre = "MichaelScott_Lip",
                            Peso = 0.0,
                            URL = "https://newfastuff.com/wp-content/uploads/2020/04/ddum8cj2d6s41.png"
                        },
                        new
                        {
                            ImagenID = 3,
                            Nombre = "Jim_Watching",
                            Peso = 0.0,
                            URL = "https://newfastuff.com/wp-content/uploads/2019/05/ml77Rv1.png"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
