// <auto-generated />
using MemGen.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MemGen.Migrations
{
    [DbContext(typeof(Connection))]
    [Migration("20211027174818_InitialCreate27")]
    partial class InitialCreate27
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.20");

            modelBuilder.Entity("MemGen.Model.Imagen", b =>
                {
                    b.Property<int>("ImagenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<double>("Peso")
                        .HasColumnType("REAL");

                    b.Property<string>("URL")
                        .HasColumnType("TEXT");

                    b.HasKey("ImagenID");

                    b.ToTable("Imagenes");

                    b.HasData(
                        new
                        {
                            ImagenID = 1,
                            Nombre = "SpongeBob_Walking",
                            Peso = 0.0,
                            URL = "https://plantillasdememes.com/img/plantillas/bob-esponja-entrando-por-la-puerta-al-salon01565047441.jpg"
                        },
                        new
                        {
                            ImagenID = 2,
                            Nombre = "MichaelScott_Lip",
                            Peso = 0.0,
                            URL = "https://newfastuff.com/wp-content/uploads/2020/04/ddum8cj2d6s41.png"
                        },
                        new
                        {
                            ImagenID = 3,
                            Nombre = "Jim_Watching",
                            Peso = 0.0,
                            URL = "https://newfastuff.com/wp-content/uploads/2019/05/ml77Rv1.png"
                        });
                });

            modelBuilder.Entity("MemGen.Model.Usuario", b =>
                {
                    b.Property<int>("UsuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nick")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.HasKey("UsuarioID");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            UsuarioID = 1,
                            Estatus = 1,
                            Nick = "alexMac",
                            Nombre = "Alejandro",
                            Password = "534b44a19bf18d20b71ecc4eb77c572f"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
